services:
  postgres:
    image: postgres
    container_name: postgres-userdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    volumes:
      - postgres_user_data:/var/lib/postgresql/data

volumes:
  postgres_user_data:
  
